# Usage: conda env create -n myenvname -f conda_dev_env.yml python=3.6
name: aiida_icl
channels:
- conda-forge
- cjs  # for sqlalchemy-diff and pgtest
dependencies:
# install_requires
- aiida-core==1.0.0b5
- ruamel.yaml
- six
# testing
- coverage
- mock==2.0.0
- pgtest==1.2.0
- pytest-cov
- pytest-regressions
- pytest-timeout
- pytest==3.6.3
- sqlalchemy-diff==0.1.3
- wheel>=0.31
# code_style
- flake8<3.8.0,>=3.7.0
- pre-commit==1.14.4
- yapf==0.26.0
