{% set name = "aiida-icl" %}
{% set version = "0.3.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: "421bd7ebb813e8c39658f9143de0186f769d5131faf36b11b7a26485ef781049"

build:
  number: 0
  noarch: "python"
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
  run:
    - aiida-core >=1.0.0b5
    - python
    - ruamel.yaml
    - setuptools
    - six

test:
  imports:
    - aiida_icl
    - aiida_icl.schedulers
    - aiida_icl.tests
    - aiida_icl.utils

about:
  home: "https://github.com/aiidateam/aiida-scheduler-cx1"
  license: "MIT"
  license_family: "MIT"
  license_file: "LICENSE"
  summary: "AiiDA plugin interfacing with the Imperial College London cx1 HPC"
  doc_url: ""
  dev_url: ""

extra:
  recipe-maintainers:
    - chrisjsewell
